config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions
  resources :welcome
  resources :articles
  resources :articles do
  resources :comments
end

resources :users do
  resources :articles


end
resources :users do
    member do
      get :confirm_email
    end
  end
  get '/login' => 'sessions#new'
 post '/login' => 'sessions#create'
 get '/logout' => 'sessions#destroy'
 get '/signup' => 'users#new'
 post '/users' => 'users#create'
  root :to => "welcome#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :article
  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  before_create :confirmation_token

  has_secure_password
  scope :user, ->(id) { where(id: id) }
  has_many :articles, dependent: :destroy
  validates :password_confirmation, presence: true, on: :create
  validates :password, confirmation: true, presence: true,
                       length: { minimum: 8 }, on: :create
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates_uniqueness_of :email
  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(validate: false)
end

  private

  def confirmation_token
    if confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
      end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base

  before_action :authorize
  # rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  # def record_not_found
  #   render plain: '404 Not Found', status: 404
  # end

  private
  #identifying the current logged in user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    # redirect_to signup_url, alert: 'Not authorized' if current_user.nil?
    current_user
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit]
  before_action :find_article_by_user, only: [:update, :destroy]
  #fetching all articles of current user
  def index
    @articles = @current_user.articles.all
    @articles = @articles.order(created_at: :desc)
  end
  #displaying selected article
  def show

  end
  #creating new article object
  def new
    @article = @current_user.articles.build
  end
  #edits article
  def edit

  end
  #creating new article with params
  def create
    @article = @current_user.articles.build(article_params)
    if @article.save

      redirect_to @article, flash: { success: 'Blog Successfully Inserted' }

    else
      flash.now[:warning] = 'Blog Insertion Failed!'
      render 'new'
    end
  end
  #Updating article
  def update
    if @article.update(article_params)
      redirect_to @article, flash: { success: 'Blog Successfully Updated' }
    else
      flash.now[:warning] = 'Blog Updation Failed'
      render 'edit'
    end
  end
  #deleting selected article
  def destroy
    @article.destroy
    if @article.destroy
      redirect_to articles_path, flash: { success: 'Blog Successfully Deleted' }
    else
      flash.now[:success] = 'Blog Deletion Failed'
      render 'show'
    end
  end

  private
  #finding the article which is in the current users ownership
  def find_article_by_user
    @article = @current_user.articles.find(params[:id])
  end
  #finding all article
  def find_article
    @article = Article.find_by_id(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :user_id)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :searcharticle
  before_action :searchcomment, only: [:show, :destroy]
  #creating new comment
  def create
    @comment = @article.comments.build(comment_params)
    if @comment.save
      flash[:success] = 'Comment inserted Successfully'
      redirect_to article_path(@article)
    else
      flash[:warning] = 'Cannot insert a blank comment'
      redirect_to article_path(@article)
    end
  end
  #destroys selected comment
  def destroy
    if @comment.destroy
      redirect_to article_path(@article), flash: { info: 'Comment Deleted Successfully' }
    else
      redirect_to article_path(@article), flash: { danger: 'Cannot Delete the comment' }
    end
  end
  #showing comment
  def show
    redirect_to article_path(@article)
  end

  private
  #finding all comments related to the article
  def searchcomment
    @comment = @article.comments.find_by_id(params[:id])
  end
  #searching articles
  def searcharticle
    @article = Article.find_by_id(params[:article_id])
  end

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authorize

  def new; end
  #creating new user object
  def create
    user = User.find_by_email(params[:email].downcase)
    if user&.authenticate(params[:password])
      if user.email_confirmed
        session[:user_id] = user.id
        redirect_to :welcome_index, flash: { success: 'Successfully Logged in' }
      else
        flash.now[:info] = 'Please activate your account by following the
        instructions in the account confirmation email you received to proceed'
        render 'new'
      end
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
  #log outing the current_user
  def destroy
    session[:user_id] = nil
    redirect_to root_url, flash: { info: 'Logged Out' }
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :authorize
  #creating new user
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.registration_confirmation(@user).deliver_now
      flash[:success] = 'Please confirm your email address to continue'
      redirect_to signup_url
    else
      flash[:danger] = 'Sorry You Cannot Sign in'
      render 'new'
    end
  end

  def new
    @user = User.new
  end
  #confirming email
  def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      session[:user_id] = nil
      flash[:success] = "Welcome to the Blog Your email has been confirmed.
        Please sign in to continue."
      redirect_to login_url
    else
      flash[:warning] = 'Sorry. User does not exist'
      redirect_to root_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController

  #showing all articles
  def index
    @articles = Article.all
    @articles = @articles.order(created_at: :desc)
    @users = User.all
   end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="container">
  <div class="new_article">
    <h1>New article</h1>
  </div>
  <div class="form-horizontal">
    <%= form_with model: @article, local: true do |form| %>

    <% if @article.errors.any? %>
      <div id="error_explanation " class="alert-danger alert-dismissible">
        <h2>
          <%= pluralize(@article.errors.count, "error") %>
          prohibited this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="new_articles form-group">
      <p >
        <%= form.label :title ,:class=>"control-label "%>
        <%= form.text_field :title ,:class=>"input_title form-control",:placeholder=>"Enter the Title" ,:id=>"focusedInput"%>
      </p>

      <p>
        <%= form.label :text %><br>
        <%= form.text_area :text ,:id => "mytextarea",:placeholder=>"Enter contents"%>
      </p>

      <p >
        <%= form.submit "Submit Article",:class=>"btn btn-success btn btn-block mybtn btn-primary tx-tfm" %>
      </p>
    </div>
  <% end %>

</div>
<%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<div class="container" style="margin-top:50px">
  <div class="link_new_article ">
    <h4><%= link_to 'Add New Article', new_article_path ,:class=>"nav-link active text-secondary"%></h4>
  </div>
  <div class="table table-hover">
    <table class="table">
      <thead>
        <tr >
          <th class="text-center">Title</th>
          <th class="text-center">Text</th>
          <th class="text-center" colspan="3">Options</th>
        </tr>
      </thead>
      <tbody>
        <% @articles.each do |article| %>
          <tr>
            <td><%= article.title %></td>
            <td><%= article.text %></td>
            <div class="btn-group">
              <td><%= link_to 'Show', article_path(article) ,:class=>"btn btn-primary"%></td>
              <td><%= link_to 'Edit', edit_article_path(article) ,:class=>"btn btn-primary"%></td>
              <td><%= button_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } ,:class=>"btn btn-primary"%></td>
            </div>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>

</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="new_article">
    <h1>New article</h1>
  </div>
  <div class="form-horizontal">
    <%= form_with model: @article, local: true do |form| %>

    <% if @article.errors.any? %>
      <div id="error_explanation " class="alert-danger alert-dismissible">
        <h2>
          <%= pluralize(@article.errors.count, "error") %>
          prohibited this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="new_articles form-group">
      <p >
        <%= form.label :title ,:class=>"control-label "%>
        <%= form.text_field :title ,:class=>"input_title form-control",:placeholder=>"Enter the Title" ,:id=>"focusedInput"%>
      </p>

      <p>
        <%= form.label :text %><br>
        <%= form.text_area :text ,:id => "mytextarea",:placeholder=>"Enter contents"%>
      </p>

      <p >
        <%= form.submit "Submit Article",:class=>"btn btn-success btn btn-block mybtn btn-primary tx-tfm" %>
      </p>
    </div>
  <% end %>

</div>
<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="container ">
  <div class="">
    <div class="show_article  mx-auto">
      <div class="logo mb-3"><br>
        <div
          class="  ">
          <h1 >

            <%= @article.title %>
          </h1>

          <p>

            <%= @article.text.html_safe %>
          </p>
        </div>
      </div>

      <div class="
          comment_section="comment_section"
          logo="logo"
          mb-3="mb-3"
          col-md-12="col-md-12"
          ">
          <h4>Comments</h4>
          <%= render @article.comments %>
          <br>
          <h4 >Add a comment</h4>
          <%= render 'comments/form' %>

        </div>
      </div </div>
      <div class="title_contents  text-center logo mb-3">
        <ul class="pager">

          <% if @current_user && @current_user.id == @article.user_id %>
            <li><%= link_to 'Edit', edit_article_path(@article) %></li>

            <li><%= link_to 'Back', articles_path %></li>
          <% else %>
            <li><%= link_to 'Back', welcome_index_path %></li>
          <% end %>
        </ul>
      </div>
    </div>

app/views/comments/_comment.html.erb
  <div >
<div class="show_article  mx-auto">
  <div class="logo mb-3"><br>
     <div class=" ">
       <h5>
         <strong>Commenter:</strong><%= comment.commenter %>
       </h5>

       <h5>
         <strong>Comment:</strong><%= comment.body %>
         <% if @current_user && @current_user.id == @article.user_id  %>
         <%= button_to 'Delete', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' } ,:class=>"btn btn-primary"%>
       </h5>
       <% end %>
     </div>
  </div>
</div>
</div>

app/views/comments/_form.html.erb
<div class=" container ">
  <div class=" row form-horizontal">
    <div class="logo "><br>
      <div class=" text-center ">
        <div class="add_comment form-horizontal">
          <%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
          <!-- <div class="comment_section "> -->
          <!-- <div class="commenter"> -->

          <div class="form-group">
            <%= form.label :commenter ,:class=>"sr-only " %>
            <%= form.text_field :commenter ,:class=>"form-control",:placeholder=>"Commenter" %>
          </div>

          <!-- </div> -->
          <div class="form-group">

            <%= form.label :body ,:class=>"sr-only col-sm-2"%>
            <%= form.text_field :body ,:class=>"comment_content form-control" ,:placeholder=>"Enter the Comment" %>

          </div>

          <%= form.submit "Create Comment",:class=>"btn btn-primary btn btn-block mybtn btn-primary tx-tfm" %>
          <div></div>
        <% end %>
        <!-- </div> -->
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<%url=Rails.application.routes.recognize_path(request.referrer)%>
  <html>
    <head>
      <title>Blog</title>

      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tag %>
      <script src="https://cdn.tiny.cloud/1/v4qiu77vllo203hcz04av8jxkqq763tq7vl5yeoh1d9wfrss/tinymce/5/tinymce.min.js"></script>
      <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
      <script>
        tinymce.init({selector: '#mytextarea'});
      </script>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
      <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->
      <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->

      <!-- Bootstrap core CSS -->
      <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->
      <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <!-- Custom fonts for this template -->
      <!-- <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"> -->
      <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
      <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
          margin-bottom: 0;
          border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
          height: 450px;
        }

        /* Set gray background color and 100% height */
        .sidenav {
          padding-top: 20px;
          background-color: #f1f1f1;
          height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
          background-color: #555;
          color: white;
          padding: 15px;
        }
        .button-nav {
          width: 14%;
          float: left;
        }
        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
          .sidenav {
            height: auto;
            padding: 35px;
          }
          .row.content {
            height: auto;
          }
        }
        .login-button {
          float: right;
        }
        .signup-button {
          float: left;
        }
      </style>

    </head>
    <body>
      <nav class="navbar  card-body bg-dark navbar-fixed-top" id="mainNav">
        <div class="container-fluid ">

          <%if @current_user  && (url[:controller] == "sessions" || url[:controller] == "users")%>
            <div class="nav ">
              <h5 class="text-light"><%= @current_user.email %></h5>
            </div>
            <ul class="nav ">

              <h3 ><%= link_to 'Home', welcome_index_path ,:class=>"nav-link active text-success"%></h3>

            </ul>
            <div class=" button-nav">

              <div class="login-button">
                <button class="btn btn-info navbar-btn"><%= link_to 'Logout', logout_path ,:class=>"nav-link text-light active"%></button</div>
              </div>
              <% elsif   @current_user %>
                <h5 class="text-light"><%= @current_user.email %></h5>

                <ul class="nav navbar-nav button-nav">
                  <li class="">
                    <h3 ><%= link_to 'Home', welcome_index_path ,:class=>"nav-link active text-success"%></h3>
                  </li>

                </ul>
                <button class="btn btn-info navbar-btn"><%= link_to 'Logout', logout_path ,:class=>"nav-link text-light active"%></button>

              <% else %>
                <div class="nav">
                  <h4 class="text-light">Welcome Guest</h4>
                </div>
                <ul class="nav ">
                  <h3 ><%= link_to 'Home', welcome_index_path ,:class=>"nav-link active text-success"%></h3>
                </ul>
                <div class=" button-nav">

                  <div class="signup-button">
                    <button class="btn btn-primary "><%= link_to 'Signup', signup_path ,:class=>"nav-link text-light active"%></button>
                  </div>
                  <div class="login-button">
                    <button class="btn btn-success "><%= link_to 'Login', login_path ,:class=>"nav-link text-light active"%></button>
                  </div>
                </div>
              <% end %>
            </div>
          </nav>

          <div class="container-fluid" style="margin-top:100px">
            <div class="user_header ">
              <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>   alert-dismissible fade show" role="alert"><%= value %></div>
              <% end %>
              <%= yield %>

            </div>
          </div>

        </body>
      </html>

app/views/users/new.html.erb
<div class="container">
  <div id="first" class="text-center">
    <% if current_user%>
      <div class="alert alert-warning">Do you want to logout?</div>
      <%= current_user.email %>.
      <%= link_to "Log Out", logout_path %>
    </div>
  <% else %>

    <div class="row">
      <div class="col-md-5 mx-auto">
        <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <div class="error_messages alert alert-danger alert-dismissible">
            <h2>Form is invalid</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div id="second">
          <div class="myform form ">
            <div class="logo mb-3">
              <div class="col-md-12 text-center">
                <h1 >Signup</h1>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :email %><br/>
              <%= f.text_field :email , :class => "form-control" ,:placeholder => "Enter your Email"%>
            </div>
            <div class="form-group">
              <%= f.label :password %><br/>
              <%= f.password_field :password , :class => "form-control" ,:placeholder => "Enter your Password"%>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation %><br/>
              <%= f.password_field :password_confirmation , :class => "form-control" ,:placeholder => "Confirm your Password"%>
            </div>
          </div>
          <div class="col-md-12 text-center mb-3">
            <div class="actions"><%= f.submit "Sign Up" ,:class=>"btn btn-block mybtn btn-primary tx-tfm"%></div>
          </div>
          <div class="col-md-12 ">
            <div class="form-group">
              <p class="text-center">Already have an account?
                <%= link_to " Log In", login_path %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>

  </div>
</div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron  card-body text-center">
  <div class="container">
    <div class="lead col-sm-2 sidenav">
      <% if @current_user %>
        <h5><%= link_to ' New Article', new_article_path ,:class=>"nav-link active text-secondary"%></h5>
      <% end %>
    </div>
    <div class=" col-sm-8">
      <h3 >MyBlog</h3></div>
  <div class="  lead col-sm-2 sidenav"  >
  <% if @current_user %>
  <h5><%= link_to 'My Articles', articles_path ,:class=>"nav-link active text-secondary"%></h5>

  <% end %>
  </div>
</div>
</div>
<div class="container">
        <div class="col-md-12">
          <% @articles.each do |article| %>

            <h2>
              <%=link_to article.title , article_path(article) ,:class=>"nav-link active text-dark"%>
              </h2>
                <p class="small">
                  <%= link_to article.text.html_safe, article_path(article) ,:class=>"nav-link active text-secondary" %></p>
              </div>
              <div>
                <p class="small text-muted">
                  Created By
                  <% @users.each do |user| %>
                    <% if article.user_id == user.id %>
                      <%= user.email %>
                    <% end %>
                  <% end %>
                  &nbsp; On
                  <%= article.created_at%>
                </p>
                <hr>
              <% end %>

            </div>